In [1]:
import glob
import os
# Ignore warnings
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter('ignore')

#Process data
import pandas as pd
import numpy as np
import xarray as xr


In [2]:
Path='/media/Data1/Climada/isimip3/ClimateData/'

## test how to calculate spatial average of xarray dataset

In [3]:
min_lon = -100 
min_lat = 35
max_lon = -75
max_lat = 45

In [4]:
fn1 = '/media/Data1/Climada/isimip3/ClimateData/gfdl-esm4_r1i1p1f1_w5e5_ssp126_pr_global_daily_2061_2070.nc'
ds=xr.open_dataset(fn1)
#crop data in the region
cropped_ds = ds.sel(lat=slice(max_lat,min_lat), lon=slice(min_lon,max_lon))
#average over the region to get time series
pr=cropped_ds['pr'].mean(dim=('lat','lon'))*3600*24

In [5]:
ds

<xarray.Dataset>
Dimensions:  (lon: 720, lat: 360, time: 3652)
Coordinates:
  * lon      (lon) float64 -179.8 -179.2 -178.8 -178.2 ... 178.8 179.2 179.8
  * lat      (lat) float64 89.75 89.25 88.75 88.25 ... -88.75 -89.25 -89.75
  * time     (time) datetime64[ns] 2061-01-01 2061-01-02 ... 2070-12-31
Data variables:
    pr       (time, lat, lon) float32 ...
Attributes:
    institution:  Potsdam Institute for Climate Impact Research (PIK)
    contact:      ISIMIP cross-sectoral science team <info@isimip.org> <https...
    references:   Lange (2019) <https://doi.org/10.5194/gmd-12-3055-2019> and...
    title:        ISIMIP3b bias-adjusted climate input data
    project:      Inter-Sectoral Impact Model Intercomparison Project phase 3...
    summary:      CMIP6 daily output data bias-adjusted and statistically dow...

In [6]:
cropped_ds

<xarray.Dataset>
Dimensions:  (lon: 50, lat: 20, time: 3652)
Coordinates:
  * lon      (lon) float64 -99.75 -99.25 -98.75 -98.25 ... -76.25 -75.75 -75.25
  * lat      (lat) float64 44.75 44.25 43.75 43.25 ... 36.75 36.25 35.75 35.25
  * time     (time) datetime64[ns] 2061-01-01 2061-01-02 ... 2070-12-31
Data variables:
    pr       (time, lat, lon) float32 0.0 0.0 0.0 ... 0.0 3.401e-06 5.259e-06
Attributes:
    institution:  Potsdam Institute for Climate Impact Research (PIK)
    contact:      ISIMIP cross-sectoral science team <info@isimip.org> <https...
    references:   Lange (2019) <https://doi.org/10.5194/gmd-12-3055-2019> and...
    title:        ISIMIP3b bias-adjusted climate input data
    project:      Inter-Sectoral Impact Model Intercomparison Project phase 3...
    summary:      CMIP6 daily output data bias-adjusted and statistically dow...

In [7]:
pr

<xarray.DataArray 'pr' (time: 3652)>
array([0.20101714, 6.7168503 , 3.3481941 , ..., 0.28408298, 0.85018003,
       5.276249  ], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2061-01-01 2061-01-02 ... 2070-12-31

In [8]:
monthly_pr=pr.resample(time='m').sum()
monthly_pr

<xarray.DataArray 'pr' (time: 120)>
array([105.53282 , 147.39415 ,  98.63546 ,  95.44745 , 123.48542 ,
       129.88461 , 115.86815 ,  94.74417 ,  76.86699 ,  62.49951 ,
        85.7399  ,  70.07687 ,  99.235596, 136.21265 ,  63.18369 ,
       102.99719 , 107.064095, 152.1554  , 155.10516 ,  82.382286,
        99.115906, 110.05655 ,  93.86155 , 115.82277 , 136.56714 ,
       100.508255,  97.970276, 110.71633 , 129.4003  ,  87.62263 ,
       106.70098 , 114.55136 ,  63.006397,  70.8066  ,  96.58857 ,
       177.26689 ,  71.20075 ,  56.990734, 106.5733  , 115.392365,
        95.15054 , 110.325195, 140.62871 ,  93.74828 , 122.91438 ,
       100.843475,  75.39252 ,  46.632713,  68.08882 ,  99.18656 ,
       147.10834 , 132.0094  , 134.92506 ,  97.795395, 147.69627 ,
       113.9933  ,  92.78611 , 111.62705 ,  78.84743 ,  96.479805,
        68.42214 ,  41.25324 , 103.854065, 162.7475  ,  97.54371 ,
        89.49564 ,  99.4216  , 127.73518 ,  99.35715 ,  94.64288 ,
        93.00415 ,  86.88708 ,  74.865585,  77.30429 ,  58.785145,
       111.79381 , 135.18597 , 146.75291 ,  92.70919 ,  92.58287 ,
        86.43228 ,  55.178844, 101.978294, 108.62973 ,  85.27601 ,
        72.19972 , 128.5877  , 126.8424  , 104.45579 , 116.24004 ,
       154.05853 ,  79.756615,  59.494473,  94.93712 , 107.7522  ,
       102.375465,  90.05391 ,  66.46819 , 101.57958 , 124.12594 ,
        96.22077 ,  78.3846  , 122.45132 , 147.86162 , 102.51165 ,
       116.68609 ,  56.3936  , 113.80656 ,  86.404076,  93.63462 ,
       100.298965, 127.0851  ,  98.263016, 152.79218 , 110.52654 ,
        99.13114 ,  40.756657,  72.65552 , 100.58364 , 109.5672  ],
      dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2061-01-31 2061-02-28 ... 2070-12-31

In [9]:
pr.groupby('time.year').sum()

<xarray.DataArray 'pr' (year: 10)>
array([1206.1755, 1317.1929, 1291.7057, 1135.793 , 1320.5436, 1164.3643,
       1142.199 , 1231.9761, 1216.5438, 1191.6986], dtype=float32)
Coordinates:
  * year     (year) int64 2061 2062 2063 2064 2065 2066 2067 2068 2069 2070

In [11]:
pr.groupby('time.season').sum('time')

<xarray.DataArray 'pr' (season: 4)>
array([2804.3442, 3453.102 , 3337.4287, 2623.3174], dtype=float32)
Coordinates:
  * season   (season) object 'DJF' 'JJA' 'MAM' 'SON'

In [12]:
seasonal_mean=pr.groupby('time.season').sum('time')
seasonal_mean.sel(season='JJA') - seasonal_mean.sel(season='DJF')

<xarray.DataArray 'pr' ()>
array(648.7578, dtype=float32)

In [13]:
fn1 = '/media/Data1/Climada/isimip3/ClimateData/gfdl-esm4_r1i1p1f1_w5e5_ssp126_pr_global_daily_2071_2080.nc'
ds=xr.open_dataset(fn1)
cropped_ds = ds.sel(lat=slice(max_lat,min_lat), lon=slice(min_lon,max_lon))
pr2=cropped_ds['pr'].mean(dim=('lat','lon'))*3600*24

In [14]:
pr2

<xarray.DataArray 'pr' (time: 3653)>
array([1.9436321 , 0.60205996, 0.09639522, ..., 4.638926  , 0.9314065 ,
       0.26360366], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2071-01-01 2071-01-02 ... 2080-12-31

In [15]:
# merge data to a long periods
xr.concat([pr1,pr2],dim='time')

NameError: name 'pr1' is not defined

In [55]:
# # Print .csv files  _*2005soc_co2_yield-mai-firr_global_annual_2006_2099.nc4
# fns=glob.glob("/media/Data1/Climada/ISIMIP/data/*rcp60_2005soc_co2_yield-mai-firr*.nc4")
# fns

In [ ]:
# gfdl-esm4_r1i1p1f1_w5e5_ssp585_tas_global_daily_2091_2100.nc
# ipsl-cm6a-lr_r1i1p1f1_w5e5_ssp585_pr_global_daily_2041_2050.nc
# mpi-esm1-2-hr_r1i1p1f1_w5e5_historical_tas_global_daily_2001_2010.nc
# mri-esm2-0_r1i1p1f1_w5e5_historical_tas_global_daily_2011_2014.nc
# ukesm1-0-ll_r1i1p1f2_w5e5_ssp126_tas_global_daily_2031_2040.nc

In [29]:
variables=['tas','pr']
models=['gfdl-esm4','ipsl-cm6a-lr','mpi-esm1-2-hr','mri-esm2-0','ukesm1-0-ll']
periods=['2015_2020',
         '2021_2030',
         '2031_2040',
         '2041_2050',
         '2051_2060',         
         '2061_2070',
         '2071_2080',  
         '2081_2090',
         '2091_2100',         
        ]
ssp=['ssp126','ssp585']

In [30]:
for i in range(5):
    for j in range(2):
        for k in range(2):
#           for kk in range(9):
            fnstr=Path+models[i]+'_r1i1p1f2_w5e5_'+ssp[j]+'_'+variables[k]+'_global_daily_'+'*.nc'
            fns=glob.glob(fnstr)
            print((models[i],ssp[j],variables[k],len(fns)))


('gfdl-esm4', 'ssp126', 'tas', 0)
('gfdl-esm4', 'ssp126', 'pr', 0)
('gfdl-esm4', 'ssp585', 'tas', 0)
('gfdl-esm4', 'ssp585', 'pr', 0)
('ipsl-cm6a-lr', 'ssp126', 'tas', 0)
('ipsl-cm6a-lr', 'ssp126', 'pr', 0)
('ipsl-cm6a-lr', 'ssp585', 'tas', 0)
('ipsl-cm6a-lr', 'ssp585', 'pr', 0)
('mpi-esm1-2-hr', 'ssp126', 'tas', 0)
('mpi-esm1-2-hr', 'ssp126', 'pr', 0)
('mpi-esm1-2-hr', 'ssp585', 'tas', 0)
('mpi-esm1-2-hr', 'ssp585', 'pr', 0)
('mri-esm2-0', 'ssp126', 'tas', 0)
('mri-esm2-0', 'ssp126', 'pr', 0)
('mri-esm2-0', 'ssp585', 'tas', 0)
('mri-esm2-0', 'ssp585', 'pr', 0)
('ukesm1-0-ll', 'ssp126', 'tas', 9)
('ukesm1-0-ll', 'ssp126', 'pr', 9)
('ukesm1-0-ll', 'ssp585', 'tas', 9)
('ukesm1-0-ll', 'ssp585', 'pr', 9)


In [31]:
fnstr

'/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_*.nc'

In [32]:
fns

['/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2015_2020.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2081_2090.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2031_2040.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2061_2070.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2051_2060.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2041_2050.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2021_2030.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2091_2100.nc',
 '/media/Data1/Climada/isimip3/ClimateData/ukesm1-0-ll_r1i1p1f2_w5e5_ssp585_pr_global_daily_2071_2080.nc']

In [33]:
# 94 years from 2006 to 2099; 4 models and 2 rcps
annual_pr=np.empty(shape=(85,5,2))
annual_tm=np.empty(shape=(85,5,2))

In [37]:
imodel=0
for model in models:
    ircp=0
    print(model)
    for rcp in ssp:
        print(rcp)
        iperiod=0
        for period in periods:
            if imodel==4:
                file=model+'_r1i1p1f2_w5e5_'+rcp+'_'+'pr_global_daily_'+period+'.nc'
            else:
                file=model+'_r1i1p1f1_w5e5_'+rcp+'_'+'pr_global_daily_'+period+'.nc'
            fullpath=Path+file
            ds=xr.open_dataset(fullpath)
            cropped_ds = ds.sel(lat=slice(max_lat,min_lat), lon=slice(min_lon,max_lon))
#average over the region to get time series
            pr=cropped_ds['pr'].mean(dim=('lat','lon'))*3600*24
#                 if not os.path.isfile(fullpath):
#                     print(fullpath)
            if iperiod==0:
                data=pr
                iperiod=1
            else:
                data=xr.concat([data,pr],dim='time')
        annualpr=data.groupby('time.year').sum().values
        annual_pr[:,imodel,ircp]=annualpr[:85]
        ircp=ircp+1
    imodel=imodel+1

gfdl-esm4
ssp126
ssp585
ipsl-cm6a-lr
ssp126
ssp585
mpi-esm1-2-hr
ssp126
ssp585
mri-esm2-0
ssp126
ssp585
ukesm1-0-ll
ssp126
ssp585


In [38]:
annualpr

array([1088.7634 , 1128.0186 , 1135.6128 , 1115.9458 , 1232.9646 ,
       1149.5433 , 1060.7349 , 1198.9265 , 1100.5754 , 1072.7046 ,
       1143.6936 , 1250.1176 , 1294.4236 , 1101.6215 , 1057.5947 ,
       1172.6963 , 1142.1685 , 1112.0991 , 1120.7953 , 1084.2422 ,
       1173.1514 , 1136.208  , 1024.1934 , 1135.5396 , 1103.1941 ,
       1302.9015 ,  961.42126, 1011.8779 , 1199.1489 ,  942.66394,
       1075.484  , 1257.0612 , 1142.6809 , 1361.9988 ,  990.49255,
       1250.3916 , 1218.7676 , 1008.3385 ,  983.61707, 1059.0127 ,
       1197.8494 , 1039.1846 , 1328.2545 , 1198.1476 , 1280.4963 ,
       1084.8552 , 1247.0737 , 1158.7411 , 1020.8906 , 1464.1838 ,
       1345.1951 , 1374.8076 , 1260.0825 , 1044.6959 , 1213.0844 ,
       1318.3682 , 1091.3372 , 1298.2502 , 1332.8596 , 1097.9641 ,
       1272.5884 , 1049.3274 , 1185.0121 , 1113.392  , 1291.9424 ,
       1270.653  , 1362.8401 , 1177.4431 , 1145.0065 , 1077.2427 ,
       1194.763  , 1164.9728 , 1242.3574 , 1227.7062 , 1312.74

In [39]:
#gfdl-esm4_r1i1p1f1_w5e5_ssp585_tas_global_daily_2091_2100.nc

In [40]:
np.save('annualPr_2ssp5Models_createdby_read_ISIMIP3b_yields.npy',annual_pr)

In [42]:

imodel=0
for model in models:
    print(model)
    ircp=0
    for rcp in ssp:
        print(rcp)
        iperiod=0
        for period in periods:
            if imodel==4:
                file=model+'_r1i1p1f2_w5e5_'+rcp+'_'+'tas_global_daily_'+period+'.nc'
            else:
                file=model+'_r1i1p1f1_w5e5_'+rcp+'_'+'tas_global_daily_'+period+'.nc'
            fullpath=Path+file
            ds=xr.open_dataset(fullpath)
            cropped_ds = ds.sel(lat=slice(max_lat,min_lat), lon=slice(min_lon,max_lon))
#average over the region to get time series
            pr=cropped_ds['tas'].mean(dim=('lat','lon'))
#                 if not os.path.isfile(fullpath):
#                     print(fullpath)
            if iperiod==0:
                data=pr
                iperiod=1
            else:
                data=xr.concat([data,pr],dim='time')
        annualpr=data.groupby('time.year').mean().values
        annual_tm[:,imodel,ircp]=annualpr[:85]
        ircp=ircp+1
    imodel=imodel+1

gfdl-esm4
ssp126
ssp585
ipsl-cm6a-lr
ssp126
ssp585
mpi-esm1-2-hr
ssp126
ssp585
mri-esm2-0
ssp126
ssp585
ukesm1-0-ll
ssp126
ssp585


In [43]:
np.save('annualTas_2ssp5Models_createdby_read_ISIMIP3b_yields.npy',annual_tm)

In [44]:
annual_tm.shape

(85, 5, 2)

## Next plot the climate change data using program "read_ISIMIP3b_yields_plot.ipynb"